# Generated by Django 5.2.8 on 2025-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
            ],
        ),
    ]
