# Generated by Django 5.2.8 on 2025-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farsi', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('english', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['farsi'],
            },
        ),
    ]
